### ISSUE TITLE
Find/implement Hausdorff distance

### ISSUE THREAD

**Issue by szympie** [PiechaczekMyller/brats#15]

**Comment by szympie** [comment]
Note that it needs to remove outliers (usually by taking 99 percentile)

**Comment by myychal** [comment]
The Hausdorff distance is already implemented in scipy -> [link](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.directed_hausdorff.html). Is it okay if we use this implementation? It operates on numpy arrays, so we would need to convert tensors to ndarrays. In the future, we could think about implementing this metric ourselves on tensors to speed up the process. 
Because it operates on 2D arrays, should we sum/average/max/min volume's slice results?
@szympie @jnalepa

**Comment by szympie** [comment]
It would work fine as a metric, however using it as a loss would not work. I think we can use it now as a metric, however we should still consider this as a major issue.

**Comment by jnalepa** [comment]
We should start with using it as a metric to assess the segmentation (it should be done exactly as in https://arxiv.org/pdf/1811.02629.pdf).

**Comment by khrynczenko** [comment]
http://loli.github.io/medpy/generated/medpy.metric.binary.hd.html#medpy.metric.binary.hd  
This package looks very usefull. It feels authors are somewhat connected to the brats challange.

**Comment by myychal** [comment]
> We should start with using it as a metric to assess the segmentation (it should be done exactly as in https://arxiv.org/pdf/1811.02629.pdf).

So we will not use it as a **loss**, just as a metric?

**Comment by myychal** [comment]
> http://loli.github.io/medpy/generated/medpy.metric.binary.hd.html#medpy.metric.binary.hd
> This package looks very usefull. It feels authors are somewhat connected to the brats challange.

Nice one, we will use it as it contains many more potentially useful metrics.
